import PublicNav from '@/components/PublicNav'
import Link from 'next/link'
const services=[
 ['Internal Risk Assessment','Score a borrower using AILIFE repayment history, savings behavior, KYC completeness, loan exposure and manual review.','/services/internal-risk'],
 ['Credit Check Request','Prepare a consent-backed CreditRegistry request. Live bureau checks activate only after AILIFE receives approved credentials and permission.','/services/request'],
 ['Bulk Applicant Screening','Submit multiple applicants for internal risk scoring, manual credit review and branch-level decision support.','/services/bulk-screening'],
 ['MFI Platform Subscription','Request access to AILIFE-powered loan, savings, collection, reporting and staff monitoring tools for partner lenders.','/services/mfi-subscription']
]
export default function Services(){return <><PublicNav/><main className="mx-auto max-w-7xl px-5 py-12"><div className="rounded-[2rem] bg-gradient-to-br from-purple-950 to-violet-900 p-10 text-white"><p className="font-black uppercase tracking-widest text-yellow-300">AILIFE Credit Services</p><h1 className="mt-2 text-5xl font-black">Credit risk and microfinance support services.</h1><p className="mt-4 max-w-3xl text-purple-100">A professional service portal for partner MFIs, cooperatives and lenders requesting risk reports, applicant screening, consent management and platform access.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2">{services.map(([t,d,h])=><Link key={t} href={h} className="card p-6 transition hover:-translate-y-1 hover:shadow-xl"><h2 className="text-2xl font-black text-purple-950">{t}</h2><p className="mt-2 text-slate-600">{d}</p><span className="mt-5 inline-flex font-black text-purple-800">Open service →</span></Link>)}</div><div className="mt-8 rounded-[2rem] bg-yellow-50 p-6 text-purple-950"><b>CreditRegistry note:</b> live bureau data requires approved subscriber credentials, customer consent and permission under the bureau agreement. AILIFE internal risk reports and manual review workflows are available immediately.</div><Link href="/services/request" className="btn btn-primary mt-8 inline-flex">Start a Credit Service Request</Link></main></>}
