import PublicNav from '@/components/PublicNav'
import Link from 'next/link'
import { CreditCard, Smartphone, ReceiptText, Building2, Globe2, ShieldCheck, Users, BadgeDollarSign } from 'lucide-react'
const services=[
 ['Internal Risk Assessment','Score borrowers using repayment behaviour, savings history, KYC completeness, loan exposure and manual review.','/services/internal-risk',ShieldCheck],
 ['Credit Check Request','Create consent-backed credit screening requests and prepare future CreditRegistry bureau checks after approval.','/services/request',CreditCard],
 ['Bulk Applicant Screening','Upload or register multiple applicants for internal risk scoring and manual credit review.','/services/bulk-screening',Users],
 ['MFI Platform Subscription','Onboard smaller lenders, cooperatives and MFIs to AILIFE-powered loan, collection and reporting tools.','/services/mfi-subscription',Building2],
 ['Bill Payment Services','Configure electricity, cable TV, data, education and utility bill-payment products with settlement controls.','/services/bill-payment',ReceiptText],
 ['Airtime & Recharge Credit','Manage airtime sales, recharge-card lending, repayment limits, agent commissions and credit monitoring.','/services/airtime-credit',Smartphone],
 ['AILIFE POS Network','Register POS devices, agents, terminals, manufacturers, inventory, field deployment and fraud monitoring.','/services/pos-network',BadgeDollarSign],
 ['SME Cross-Border Desk','Capture SME trade-payment requests, Nigeria–China supplier payments, compliance review and payout tracking.','/services/sme-remittance',Globe2]
]
export default function Services(){return <><PublicNav/><main className="mx-auto max-w-7xl px-5 py-12"><div className="rounded-[2rem] bg-gradient-to-br from-purple-950 to-violet-900 p-10 text-white"><p className="font-black uppercase tracking-widest text-yellow-300">AILIFE Financial Services</p><h1 className="mt-2 text-5xl font-black">Credit, payments, POS and SME finance services.</h1><p className="mt-4 max-w-3xl text-purple-100">A professional service portal for microfinance operations, credit assessment, bill payment, airtime credit, POS network management and SME trade-payment support.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2">{services.map(([t,d,h,Icon])=><Link key={t} href={h} className="card p-6 transition hover:-translate-y-1 hover:shadow-xl"><Icon className="text-purple-800"/><h2 className="mt-3 text-2xl font-black text-purple-950">{t}</h2><p className="mt-2 text-slate-600">{d}</p><span className="mt-5 inline-flex font-black text-purple-800">Open service →</span></Link>)}</div><div className="mt-8 rounded-[2rem] bg-yellow-50 p-6 text-purple-950"><b>Compliance control:</b> bureau data, regulated payments, POS acquiring, wallet services and cross-border transfers remain disabled until AILIFE obtains the required partner agreements, licenses or approved provider credentials. Internal requests, risk scoring, service-client onboarding and review workflows are available immediately.</div><Link href="/services/request" className="btn btn-primary mt-8 inline-flex">Start a Credit Service Request</Link></main></>}
