'use client'
import { useEffect,useState } from 'react'

const datasets=['customers','loans','transactions','contributions','credit_events','decision_runs','staff_profiles']
const money=n=>Number(n||0).toLocaleString('en-NG',{style:'currency',currency:'NGN'})
export default function DataWorkbench(){
 const [dataset,setDataset]=useState('customers'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[data,setData]=useState({columns:[],rows:[]}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const [tx,setTx]=useState({customer_id:'',loan_id:'',type:'deposit',amount:'',channel:'cash',description:''})
 async function load(){setBusy(true);setMsg('');const p=new URLSearchParams({dataset,limit:'50'});if(search)p.set('search',search);if(status)p.set('status',status);const r=await fetch('/api/data-workbench?'+p);const j=await r.json();if(!r.ok)setMsg(j.error||'Query failed');else setData(j);setBusy(false)}
 useEffect(()=>{load()},[dataset])
 async function post(body){setBusy(true);setMsg('');const r=await fetch('/api/data-workbench',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?(j.message||`Completed. ${j.affected??1} record(s) affected.`):(j.error||'Operation failed'));setBusy(false);if(r.ok)load()}
 return <div className="space-y-6"><div><div className="text-xs font-black uppercase tracking-widest text-purple-700">AIBLE controlled data access</div><h1 className="text-3xl font-black text-purple-950">Data & Transaction Workbench</h1><p className="mt-2 text-slate-600">Query approved production datasets and run controlled staff transactions. SQL remains server-side, parameterized, role-scoped and audited.</p></div>
 <div className="grid gap-4 rounded-3xl border bg-white p-5 lg:grid-cols-5"><label className="font-bold">Dataset<select className="mt-2 w-full rounded-xl border p-3" value={dataset} onChange={e=>setDataset(e.target.value)}>{datasets.map(x=><option key={x}>{x}</option>)}</select></label><label className="font-bold lg:col-span-2">Search<input className="mt-2 w-full rounded-xl border p-3" placeholder="Name, phone, email or reference" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="font-bold">Status<input className="mt-2 w-full rounded-xl border p-3" placeholder="e.g. active" value={status} onChange={e=>setStatus(e.target.value)}/></label><button disabled={busy} onClick={load} className="self-end rounded-xl bg-purple-700 p-3 font-bold text-white">{busy?'Working…':'Query data'}</button></div>
 {msg&&<div className="rounded-2xl border bg-amber-50 p-4 font-semibold">{msg}</div>}
 <div className="overflow-x-auto rounded-3xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{data.columns.map(c=><th key={c} className="p-3 text-left">{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{data.rows.map((r,i)=><tr key={r.id||i} className="border-t">{data.columns.map(c=><td key={c} className="whitespace-nowrap p-3">{['amount','principal','outstanding_balance'].includes(c)?money(r[c]):String(r[c]??'')}</td>)}</tr>)}</tbody></table>{!data.rows.length&&<div className="p-8 text-center text-slate-500">No matching records.</div>}</div>
 <div className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black text-purple-950">Run controlled transaction</h2><p className="mb-4 text-sm text-slate-600">Creates a pending transaction under existing approval controls; it does not bypass maker-checker.</p><div className="grid gap-3 md:grid-cols-3"><label className="font-bold">Customer ID<input className="mt-1 w-full rounded-xl border p-3" value={tx.customer_id} onChange={e=>setTx({...tx,customer_id:e.target.value})}/></label><label className="font-bold">Loan ID (optional)<input className="mt-1 w-full rounded-xl border p-3" value={tx.loan_id} onChange={e=>setTx({...tx,loan_id:e.target.value})}/></label><label className="font-bold">Transaction type<select className="mt-1 w-full rounded-xl border p-3" value={tx.type} onChange={e=>setTx({...tx,type:e.target.value})}><option>deposit</option><option>withdrawal</option><option>loan_repayment</option><option>fee</option><option>adjustment</option></select></label><label className="font-bold">Amount (₦)<input type="number" min="0" step="0.01" className="mt-1 w-full rounded-xl border p-3" value={tx.amount} onChange={e=>setTx({...tx,amount:e.target.value})}/></label><label className="font-bold">Channel<select className="mt-1 w-full rounded-xl border p-3" value={tx.channel} onChange={e=>setTx({...tx,channel:e.target.value})}><option>cash</option><option>bank_transfer</option><option>pos</option><option>mobile_money</option><option>ussd</option><option>agent</option><option>manual</option></select></label><label className="font-bold">Description<input className="mt-1 w-full rounded-xl border p-3" value={tx.description} onChange={e=>setTx({...tx,description:e.target.value})}/></label></div><button disabled={busy} onClick={()=>post({action:'record_transaction',...tx})} className="mt-4 rounded-xl bg-purple-700 px-6 py-3 font-bold text-white">Preview & create pending transaction</button></div>
 <div className="rounded-3xl border border-purple-200 bg-purple-50 p-5"><h2 className="font-black text-purple-950">Safety model</h2><p className="mt-1 text-sm text-slate-700">Datasets and fields are allow-listed. Branch scope follows the signed-in staff session. Financial writes are parameterized and transactional. New transactions enter pending status and continue through existing approval controls. Every workbench execution is logged.</p></div></div>
}
