import Link from 'next/link'
import { requireUser } from '@/lib/auth'
import { query } from '@/lib/db'
export const dynamic='force-dynamic'
const roleNames={super_admin:'Super Admin',admin:'Admin',executive_director:'Executive Director',program_director:'Program Director',program_manager:'Program Manager',area_manager:'Area Manager',branch_manager:'Branch Manager',credit_officer:'Credit Officer',accountant:'Accountant',program_officer:'Program Officer',finance_officer:'Finance Officer',compliance_officer:'Compliance Officer',auditor:'Auditor',agent_supervisor:'Agent Supervisor',teller:'Teller'}
const work={credit_officer:[['Customers & KYC','/dashboard/customers'],['Client Onboarding','/dashboard/client-onboarding'],['Loans','/dashboard/loans'],['Credit Bureau','/dashboard/credit-bureau'],['Risk Scoring','/dashboard/risk-scoring']],branch_manager:[['Branch Operations','/dashboard/operations'],['Customers & KYC','/dashboard/customers'],['Loans','/dashboard/loans'],['Maker-Checker','/dashboard/approvals'],['Branch Cash','/dashboard/cash']],accountant:[['Transactions','/dashboard/transactions'],['Double-Entry Ledger','/dashboard/ledger'],['Branch Cash','/dashboard/cash'],['Reports','/dashboard/reports']],finance_officer:[['Transactions','/dashboard/transactions'],['Double-Entry Ledger','/dashboard/ledger'],['Maker-Checker','/dashboard/approvals'],['Reports','/dashboard/reports']],teller:[['Customers','/dashboard/customers'],['Data Workbench','/dashboard/data-workbench'],['Branch Cash','/dashboard/cash']],compliance_officer:[['KYC Documents','/dashboard/documents'],['Manual Credit Review','/dashboard/manual-credit-review'],['Fraud Alerts','/dashboard/alerts'],['Reports','/dashboard/reports']]}
export default async function Workspace(){const u=await requireUser();let counts={customers:0,loans:0,pending:0,tasks:0};try{const branch=u.can_view_all_branches?null:u.branch_id;const [c,l,p,t]=await Promise.all([query(`select count(*)::int n from customers ${branch?'where branch_id=$1':''}`,branch?[branch]:[]),query(`select count(*)::int n from loans ${branch?'where branch_id=$1':''}`,branch?[branch]:[]),query(`select count(*)::int n from transactions where status='pending' ${branch?'and branch_id=$1':''}`,branch?[branch]:[]),query(`select count(*)::int n from tasks where status not in ('completed','cancelled') ${u.id?'and (assigned_to=$1 or assigned_to is null)':''}`,u.id?[u.id]:[])]);counts={customers:c.rows[0].n,loans:l.rows[0].n,pending:p.rows[0].n,tasks:t.rows[0].n}}catch{}
 const links=work[u.role]||[['Operations Center','/dashboard/operations'],['Data Workbench','/dashboard/data-workbench'],['Customers & KYC','/dashboard/customers'],['Loans','/dashboard/loans'],['Transactions','/dashboard/transactions'],['Reports','/dashboard/reports']]
 return <div className="space-y-7"><div><div className="text-xs font-black uppercase tracking-widest text-purple-700">My work</div><h1 className="mt-2 text-4xl font-black text-purple-950">Welcome, {u.name||'Staff'}</h1><p className="mt-2 text-slate-600">{roleNames[u.role]||u.role} · {u.branch||'Head Office / all permitted branches'}. Your workspace is scoped by your signed-in role and branch.</p></div><div className="grid gap-4 md:grid-cols-4">{[['Customers',counts.customers],['Loans',counts.loans],['Pending transactions',counts.pending],['Open tasks',counts.tasks]].map(([a,b])=><div key={a} className="card p-5"><div className="text-sm font-bold text-slate-500">{a}</div><div className="mt-2 text-3xl font-black">{b}</div></div>)}</div><div className="card p-6"><h2 className="text-xl font-black text-purple-950">Work areas available to you</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{links.map(([label,href])=><Link key={href} href={href} className="rounded-2xl border p-5 font-black hover:border-purple-400 hover:bg-purple-50">{label}<div className="mt-1 text-sm font-normal text-slate-500">Open workspace →</div></Link>)}</div></div></div>}
