import PublicNav from '@/components/PublicNav'
import Link from 'next/link'
import { ShieldCheck, Smartphone, Users, BellRing, LineChart, LockKeyhole, SearchCheck, BadgeDollarSign, Building2, Landmark, ClipboardCheck, GraduationCap } from 'lucide-react'
const features=[
 ['Remote client onboarding','Create customer profiles from any branch or field location with BVN/NIN, guarantor, business profile and consent capture.',Users],
 ['Loans, savings and repayments','Manage daily, weekly and monthly loans, savings collections, disbursements, repayments and outstanding balances.',Smartphone],
 ['Real-time transaction alerts','Notify clients and staff for deposits, withdrawals, disbursements, repayments and overdue loan reminders.',BellRing],
 ['Fraud and governance control','Monitor duplicate identities, unusual withdrawals, maker-checker breaches, branch cash movement and risky staff activity.',ShieldCheck],
 ['Board and investor reporting','Provide portfolio, savings, arrears, PAR, branch performance, staff portfolio and audit reports to leadership.',LineChart],
 ['Mandatory 2FA security','Protect staff, admin and investor access with authenticator-code verification, role separation and audit trails.',LockKeyhole],
 ['Credit bureau readiness','Prepare CreditRegistry checks, consent forms, manual credit review and contributor upload queues for approved credentials.',SearchCheck],
 ['Credit services revenue','Offer internal risk reports, credit-check requests, service-client onboarding and billing for partner MFIs.',BadgeDollarSign],
 ['MFI SaaS expansion','Operate AILIFE internally while preparing subscription-based services for smaller lenders and cooperatives.',Building2],
 ['Staff onboarding','Register new workers, assign roles, branch access, onboarding checklist and testing credentials.',ClipboardCheck],
 ['Training academy','Guide staff through platform usage, loan workflow, collections, fraud controls, KYC and data protection.',GraduationCap],
 ['Branch portfolio visibility','Track Head Office, Osun, Ibadan and Port Harcourt branch status, collections and performance.',Landmark]
]
const metrics=[['Active Branches','7'],['Loan Products','3'],['Approval Limit','₦400k'],['Default Penalty','5%'],['2FA','Enabled'],['Bureau Mode','Ready']]
export default function Home(){return <><PublicNav/><section className="relative overflow-hidden bg-gradient-to-br from-purple-950 via-purple-900 to-slate-950 text-white"><div className="absolute inset-0 opacity-25 bg-[radial-gradient(circle_at_15%_20%,#facc15,transparent_25%),radial-gradient(circle_at_80%_10%,#a855f7,transparent_30%)]"/><div className="relative mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-2 lg:items-center"><div><div className="mb-5 inline-flex rounded-full bg-yellow-400/20 px-4 py-2 text-sm font-black text-yellow-200">AILIFE Empowerment Digital Finance</div><h1 className="text-5xl font-black tracking-tight lg:text-7xl">Microfinance operations, credit intelligence and staff governance in one platform.</h1><p className="mt-6 max-w-xl text-lg text-purple-100">Built for customer onboarding, savings, loans, repayment monitoring, staff performance, branch control, fraud alerts, 2FA access, credit bureau readiness and executive visibility.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/onboard" className="btn btn-gold">Open Customer Account</Link><Link href="/login" className="btn bg-white text-purple-950">Staff Login</Link><Link href="/admin-login" className="btn border border-white/40 text-white">Admin Login</Link><Link href="/investor-login" className="btn border border-white/40 text-white">Investor Login</Link></div></div><div className="rounded-[2rem] bg-white p-6 text-slate-900 shadow-2xl"><div className="grid gap-4 sm:grid-cols-2">{metrics.map(([x,y])=><div key={x} className="rounded-3xl border border-purple-100 bg-purple-50 p-5"><div className="text-sm font-bold text-purple-700">{x}</div><div className="mt-2 text-3xl font-black text-purple-950">{y}</div></div>)}</div><div className="mt-5 rounded-3xl bg-slate-950 p-5 text-white"><div className="font-black text-yellow-300">Governance by design</div><p className="mt-2 text-sm text-purple-100">Maker-checker approvals, staff role separation, credit officer review, branch manager recommendation, Area Manager/Program Director approval and accountant control.</p></div></div></div></section><section className="mx-auto max-w-7xl px-5 py-16"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="font-black uppercase tracking-widest text-purple-700">Production modules</p><h2 className="mt-2 text-4xl font-black text-slate-950">Operational pages are connected for testing.</h2></div><Link href="/dashboard" className="btn btn-primary">Open Command Center</Link></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([t,d,Icon])=><div key={t} className="card p-6"><Icon className="text-purple-800"/><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-2 text-slate-600">{d}</p></div>)}</div></section></>}
