import Link from 'next/link'
import { Menu, LayoutDashboard, Workflow, Database, Users, Banknote, ReceiptText, ShieldAlert, UserCog, BarChart3, Settings, Scale, CheckCircle2, Warehouse, Store, FileText, Bell, Building2, GraduationCap, SearchCheck, Settings2, BrainCircuit, ClipboardList, ClipboardCheck, Network, Landmark, HandCoins, Building, BadgeDollarSign, FileSignature, UploadCloud, KeyRound, TrendingUp, UsersRound, PlugZap, BriefcaseBusiness, ArrowLeftRight } from 'lucide-react'
import LogoutButton from './LogoutButton'
import { getCurrentUser } from '@/lib/auth'
const A=['super_admin','admin','executive_director','program_director'],M=[...A,'program_manager','area_manager','branch_manager'],F=[...A,'accountant','finance_officer']
const nav=[
 ['/dashboard/workspace','My Workspace',BriefcaseBusiness,null],['/dashboard','Command Center',LayoutDashboard,M],['/dashboard/operations','Operations Center',Workflow,null],['/dashboard/data-workbench','Data Workbench',Database,null],['/dashboard/fx','FX Rates & Estimator',ArrowLeftRight,F],['/dashboard/branches','Branches',Building2,M],['/dashboard/org-structure','Org Structure',Network,M],['/dashboard/customers','Customers/KYC',Users,null],['/dashboard/groups','Groups / Ajo SaaS',UsersRound,M],['/dashboard/integrations','Fintech Integrations',PlugZap,A],['/dashboard/client-onboarding','Client Onboarding',ClipboardCheck,null],['/dashboard/loans','Loans',Banknote,null],['/dashboard/loan-products','Loan Products',Landmark,M],['/dashboard/approval-rules','Approval Rules',CheckCircle2,M],['/dashboard/transactions','Transactions',ReceiptText,null],['/dashboard/ledger','Double-Entry Ledger',Scale,F],['/dashboard/approvals','Maker-Checker',CheckCircle2,M],['/dashboard/cash','Branch Cash',Warehouse,null],['/dashboard/agents','Agent Banking',Store,M],['/dashboard/documents','KYC Documents',FileText,null],['/dashboard/notifications','SMS/Email Outbox',Bell,M],['/dashboard/credit-history','Credit History 360',FileText,null],['/dashboard/decision-rules','Decision Rules Engine',BrainCircuit,M],['/dashboard/credit-bureau','Credit Bureau',SearchCheck,null],['/dashboard/credit-config','Bureau Config',Settings2,A],['/dashboard/risk-scoring','Risk Scoring',BrainCircuit,null],['/dashboard/manual-credit-review','Manual Credit Review',ClipboardList,null],['/dashboard/credit-services','Credit Services',HandCoins,M],['/dashboard/service-clients','Service Clients',Building,M],['/dashboard/credit-check-sales','Credit Check Sales',BadgeDollarSign,M],['/dashboard/consent-forms','Consent Forms',FileSignature,null],['/dashboard/bureau-uploads','Bureau Upload Queue',UploadCloud,M],['/dashboard/saas-platform','MFI SaaS Platform',Store,A],['/dashboard/api-access','Future API Access',KeyRound,A],['/dashboard/revenue','Revenue',TrendingUp,F],['/dashboard/alerts','Fraud Alerts',ShieldAlert,null],['/dashboard/staff','Staff & Roles',UserCog,A],['/dashboard/staff-management','Staff Management',UserCog,A],['/dashboard/staff-onboarding','Staff Onboarding',ClipboardCheck,A],['/dashboard/training','Staff Training',GraduationCap,M],['/dashboard/onboarding-checklist','Onboarding Checklists',ClipboardCheck,M],['/dashboard/reports','Regulatory Reports',BarChart3,M],['/dashboard/settings','Governance',Settings,A],['/dashboard/admin/migrations','Migration Center',Database,['super_admin']]
]
function NavLinks({visible,mobile=false}){return <div className={mobile?'grid gap-1':'space-y-1'}>{visible.map(([href,label,Icon])=><Link key={href} href={href} className="flex min-h-11 items-center gap-3 rounded-2xl px-4 py-3 font-bold text-slate-700 hover:bg-purple-50 hover:text-purple-900"><Icon size={18} className="shrink-0"/><span>{label}</span></Link>)}</div>}
export default async function AppShell({children}){const u=await getCurrentUser();const visible=nav.filter(x=>!x[3]||x[3].includes(u?.role));return <div className="min-h-screen bg-slate-50">
<aside className="fixed inset-y-0 left-0 hidden w-80 overflow-y-auto border-r bg-white p-5 lg:block"><div className="mb-8"><div className="text-2xl font-black text-purple-950">AIBLE Command</div><div className="text-sm text-slate-500">Digital Finance Operations</div><div className="mt-3 rounded-xl bg-purple-50 p-3 text-xs"><b>{u?.name}</b><br/>{String(u?.role||'').replaceAll('_',' ')}{u?.branch?` · ${u.branch}`:''}</div></div><NavLinks visible={visible}/><div className="sticky bottom-0 mt-6 border-t bg-white py-4"><LogoutButton/></div></aside>
<header className="fixed inset-x-0 top-0 z-50 border-b bg-white/95 px-3 py-2 shadow-sm backdrop-blur lg:hidden"><div className="flex items-center gap-2"><details className="group relative min-w-0 flex-1"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 rounded-xl border border-slate-200 px-3 font-black text-purple-950"><Menu size={20}/><span className="truncate">AIBLE Menu</span></summary><div className="fixed inset-x-2 top-[60px] max-h-[calc(100vh-70px)] overflow-y-auto rounded-2xl border bg-white p-3 shadow-2xl"><div className="mb-3 rounded-xl bg-purple-50 p-3 text-xs"><b>{u?.name}</b><br/>{String(u?.role||'').replaceAll('_',' ')}{u?.branch?` · ${u.branch}`:''}</div><NavLinks visible={visible} mobile/><div className="sticky bottom-0 mt-3 border-t bg-white pt-3"><LogoutButton/></div></div></details><div className="w-28 shrink-0"><LogoutButton compact/></div></div></header>
<main className="min-w-0 pt-16 lg:pl-80 lg:pt-0"><div className="mx-auto min-w-0 max-w-7xl p-3 sm:p-5 lg:p-8">{children}</div></main></div>}
