'use client'
import { useEffect,useState } from 'react'
const labels={admin:'Admin',executive_director:'Executive Director',program_director:'Program Director',program_manager:'Program Manager',area_manager:'Area Manager',branch_manager:'Branch Manager',credit_officer:'Credit Officer',accountant:'Accountant',program_officer:'Program Officer',finance_officer:'Finance Officer',compliance_officer:'Compliance Officer',auditor:'Auditor',agent_supervisor:'Agent Supervisor',teller:'Teller',secretary:'Secretary',receptionist:'Receptionist'}
const initial={fullName:'',email:'',phone:'',department:'Operations',role:'credit_officer',branchId:'',area:'',approvalLimit:'0',mfaRequired:true,canViewAllBranches:false,startDate:''}
export default function StaffOnboardingClient(){
 const [data,setData]=useState({staff:[],branches:[],roles:[],can_manage:false}),[form,setForm]=useState(initial),[busy,setBusy]=useState(true),[msg,setMsg]=useState(''),[credential,setCredential]=useState(null)
 async function load(){setBusy(true);const r=await fetch('/api/staff',{cache:'no-store'});const j=await r.json();if(r.ok)setData(j);else setMsg(j.error||'Unable to load staff');setBusy(false)}
 useEffect(()=>{load()},[])
 async function submit(e){e.preventDefault();setBusy(true);setMsg('');setCredential(null);const r=await fetch('/api/staff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)setMsg(j.error||'Could not create staff');else{setCredential({email:j.staff.email,password:j.temporaryPassword,name:j.staff.full_name});setForm(initial);setMsg(`${j.staff.full_name} was created successfully.`);await load()}setBusy(false)}
 return <div className="space-y-7"><div><h1 className="text-4xl font-black text-purple-950">Staff Onboarding</h1><p className="mt-2 text-slate-600">Create staff login, assign role and branch, require MFA and issue first-login credentials.</p></div>
 {data.can_manage&&<form onSubmit={submit} className="card p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black text-purple-950">+ Add Staff</h2><span className="badge bg-purple-100 text-purple-900">{data.staff.length} staff</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Full name"><input className="input" required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Field><Field label="Email"><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Phone"><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Role"><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{data.roles.map(r=><option key={r} value={r}>{labels[r]||r}</option>)}</select></Field><Field label="Branch"><select className="input" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">No branch / HQ</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Department"><input className="input" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></Field><Field label="Area"><input className="input" value={form.area} onChange={e=>setForm({...form,area:e.target.value})}/></Field><Field label="Approval limit (₦)"><input className="input" type="number" min="0" value={form.approvalLimit} onChange={e=>setForm({...form,approvalLimit:e.target.value})}/></Field><Field label="Start date"><input className="input" type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field></div><div className="mt-5 flex flex-wrap gap-6"><label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={form.mfaRequired} onChange={e=>setForm({...form,mfaRequired:e.target.checked})}/> Require MFA</label><label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={form.canViewAllBranches} onChange={e=>setForm({...form,canViewAllBranches:e.target.checked})}/> View all branches</label></div><button disabled={busy} className="btn btn-primary mt-5">{busy?'Saving…':'Create staff & issue temporary password'}</button></form>}
 {msg&&<div className="rounded-2xl border bg-white p-4 font-semibold">{msg}</div>}{credential&&<div className="rounded-2xl border-2 border-purple-300 bg-purple-50 p-5"><h3 className="font-black text-purple-950">Temporary credentials — copy now</h3><p className="mt-2">Email: <b>{credential.email}</b></p><p>Password: <code className="rounded bg-white px-2 py-1 font-black">{credential.password}</code></p><p className="mt-2 text-sm text-slate-600">The user will be forced to change this password. MFA setup follows when required. The password is not stored in readable form.</p></div>}
 <div className="card overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-black">Staff accounts</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Name','Email','Role','Branch','MFA','Status','Created'].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{data.staff.map(s=><tr key={s.id} className="border-t"><td className="p-4 font-bold">{s.full_name}</td><td>{s.email}</td><td>{labels[s.role]||s.role}</td><td>{s.branch||'HQ'}</td><td>{s.mfa_required?'Required':'Optional'}</td><td>{s.status}</td><td>{new Date(s.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!data.staff.length&&!busy&&<div className="p-8 text-center text-slate-500">No staff accounts yet.</div>}</div></div></div>
}
function Field({label,children}){return <label className="grid gap-2 text-sm font-bold text-slate-700"><span>{label}</span>{children}</label>}
