'use client'
import { useEffect,useState } from 'react'
const labels={admin:'Admin',executive_director:'Executive Director',program_director:'Program Director',program_manager:'Program Manager',area_manager:'Area Manager',branch_manager:'Branch Manager',credit_officer:'Credit Officer',accountant:'Accountant',program_officer:'Program Officer',finance_officer:'Finance Officer',compliance_officer:'Compliance Officer',auditor:'Auditor',agent_supervisor:'Agent Supervisor',teller:'Teller',secretary:'Secretary',receptionist:'Receptionist',super_admin:'Super Admin'}
const initial={fullName:'',email:'',phone:'',department:'Operations',role:'credit_officer',branchId:'',area:'',approvalLimit:'0',mfaRequired:true,canViewAllBranches:false,startDate:''}
export default function StaffOnboardingClient(){
 const [data,setData]=useState({staff:[],branches:[],roles:[],can_manage:false,is_super_admin:false}),[form,setForm]=useState(initial),[busy,setBusy]=useState(true),[msg,setMsg]=useState(''),[credential,setCredential]=useState(null),[selected,setSelected]=useState(null)
 async function load(){setBusy(true);const r=await fetch('/api/staff',{cache:'no-store'});const j=await r.json();if(r.ok)setData(j);else setMsg(j.error||'Unable to load staff');setBusy(false)}
 useEffect(()=>{load()},[])
 async function submit(e){e.preventDefault();setBusy(true);setMsg('');setCredential(null);const r=await fetch('/api/staff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)setMsg(j.error||'Could not create staff');else{setCredential({email:j.staff.email,password:j.temporaryPassword,name:j.staff.full_name});setForm(initial);setMsg(`${j.staff.full_name} was created successfully.`);await load()}setBusy(false)}
 async function manage(staff,action){
  if(action==='remove'&&!confirm(`Remove ${staff.full_name}'s login? This keeps the account record for audit history but blocks access.`))return
  if(action==='suspend'&&!confirm(`Suspend ${staff.full_name}? They will no longer be able to sign in.`))return
  setBusy(true);setMsg('');setCredential(null)
  const body={id:staff.id}
  if(action==='password')body.resetPassword=true
  if(action==='mfa')body.resetMfa=true
  if(action==='suspend')body.status='Suspended'
  if(action==='activate')body.status='Active'
  if(action==='remove')body.status='Removed'
  const r=await fetch('/api/staff',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json()
  if(!r.ok)setMsg(j.error||'Unable to update staff account')
  else{if(j.temporaryPassword)setCredential({email:staff.email,password:j.temporaryPassword,name:staff.full_name});setMsg(action==='password'?`New temporary password generated for ${staff.full_name}.`:action==='mfa'?`MFA reset for ${staff.full_name}.`:action==='activate'?`${staff.full_name} reactivated.`:action==='suspend'?`${staff.full_name} suspended.`:`${staff.full_name} removed from active access.`);await load()}
  setBusy(false)
 }
 function canManageRow(s){if(!data.can_manage)return false;if(s.role==='super_admin')return false;if(!data.is_super_admin&&s.role==='admin')return false;return true}
 return <div className="space-y-7"><div><h1 className="text-4xl font-black text-purple-950">Staff Onboarding & Account Management</h1><p className="mt-2 text-slate-600">Create staff logins, assign roles and branches, issue temporary credentials, reset MFA, suspend or reactivate access.</p></div>
 {data.can_manage&&<form onSubmit={submit} className="card p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black text-purple-950">+ Add Staff</h2><span className="badge bg-purple-100 text-purple-900">{data.staff.length} staff</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Full name"><input className="input" required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Field><Field label="Email"><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Phone"><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Role"><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{data.roles.map(r=><option key={r} value={r}>{labels[r]||r}</option>)}</select></Field><Field label="Branch"><select className="input" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">No branch / HQ</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Department"><input className="input" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></Field><Field label="Area"><input className="input" value={form.area} onChange={e=>setForm({...form,area:e.target.value})}/></Field><Field label="Approval limit (₦)"><input className="input" type="number" min="0" value={form.approvalLimit} onChange={e=>setForm({...form,approvalLimit:e.target.value})}/></Field><Field label="Start date"><input className="input" type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field></div><div className="mt-5 flex flex-wrap gap-6"><label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={form.mfaRequired} onChange={e=>setForm({...form,mfaRequired:e.target.checked})}/> Require MFA</label><label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={form.canViewAllBranches} onChange={e=>setForm({...form,canViewAllBranches:e.target.checked})}/> View all branches</label></div><button disabled={busy} className="btn btn-primary mt-5">{busy?'Saving…':'Create staff & issue temporary password'}</button></form>}
 {msg&&<div className="rounded-2xl border bg-white p-4 font-semibold">{msg}</div>}{credential&&<div className="rounded-2xl border-2 border-purple-300 bg-purple-50 p-5"><h3 className="font-black text-purple-950">Temporary credentials — copy now</h3><p className="mt-2">Email: <b>{credential.email}</b></p><p>Password: <code className="rounded bg-white px-2 py-1 font-black">{credential.password}</code></p><p className="mt-2 text-sm text-slate-600">This password is shown once. The user must change it on first login. It is stored only as a secure hash.</p></div>}
 <div className="card overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-black">Staff accounts</h2><p className="mt-1 text-sm text-slate-500">Select Manage to control an existing account. “Remove access” preserves the record for audit history.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Name','Email','Role','Branch','MFA','Status','Created','Actions'].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{data.staff.map(s=><tr key={s.id} className="border-t"><td className="p-4 font-bold">{s.full_name}</td><td className="p-3">{s.email}</td><td className="p-3">{labels[s.role]||s.role}</td><td className="p-3">{s.branch||'HQ'}</td><td className="p-3">{s.mfa_required?'Required':'Optional'}</td><td className="p-3"><span className={`badge ${String(s.status).toLowerCase()==='active'?'bg-green-100 text-green-800':'bg-amber-100 text-amber-900'}`}>{s.status}</span></td><td className="p-3">{new Date(s.created_at).toLocaleDateString()}</td><td className="p-3">{canManageRow(s)?<button type="button" className="btn" onClick={()=>setSelected(selected?.id===s.id?null:s)}>Manage</button>:<span className="text-xs text-slate-400">Protected</span>}</td></tr>)}</tbody></table>{!data.staff.length&&!busy&&<div className="p-8 text-center text-slate-500">No staff accounts yet.</div>}</div></div>
 {selected&&<div className="card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black text-purple-950">Manage {selected.full_name}</h2><p className="text-sm text-slate-500">{selected.email} · {labels[selected.role]||selected.role} · {selected.branch||'HQ'}</p></div><button className="btn" onClick={()=>setSelected(null)}>Close</button></div><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} className="btn btn-primary" onClick={()=>manage(selected,'password')}>Generate temporary password</button><button disabled={busy} className="btn" onClick={()=>manage(selected,'mfa')}>Reset MFA</button>{String(selected.status).toLowerCase()==='active'?<button disabled={busy} className="btn" onClick={()=>manage(selected,'suspend')}>Suspend account</button>:<button disabled={busy} className="btn btn-primary" onClick={()=>manage(selected,'activate')}>Reactivate account</button>}<button disabled={busy} className="btn" onClick={()=>manage(selected,'remove')}>Remove access</button></div><p className="mt-4 text-xs text-slate-500">Suspended or removed accounts cannot sign in. Account records remain for audit and historical transaction integrity.</p></div>}
 </div>
}
function Field({label,children}){return <label className="grid gap-2 text-sm font-bold text-slate-700"><span>{label}</span>{children}</label>}
