import { countRows, sumWhere } from '@/lib/db'
import { Users, Banknote, ReceiptText, ShieldAlert, Scale, CheckCircle2, Warehouse, Store, Building2, GraduationCap, ClipboardCheck } from 'lucide-react'
export default async function Dashboard(){
 const [customers,loans,tx,alerts,ledger,approvals,cash,agents,branches,loanProducts,staffOnboarding,clientOnboarding,training,deposits,withdrawals]=await Promise.all([
  countRows('customers'),countRows('loans'),countRows('transactions'),countRows('risk_alerts'),countRows('ledger_entries'),countRows('approval_workflows'),countRows('branch_cash_accounts'),countRows('agents'),countRows('branches'),countRows('loan_products'),countRows('staff_onboarding_cases'),countRows('client_onboarding_cases'),countRows('training_modules'),sumWhere('transactions','amount','type','deposit','status','approved'),sumWhere('transactions','amount','type','withdrawal','status','approved')
 ]);
 const cards=[['Branches',branches,Building2],['Customers',customers,Users],['Client Onboarding',clientOnboarding,ClipboardCheck],['Loans',loans,Banknote],['Loan Products',loanProducts,Banknote],['Transactions',tx,ReceiptText],['Open Alerts',alerts,ShieldAlert],['Credit Checks','Ready',ShieldAlert],['Ledger Entries',ledger,Scale],['Pending Approvals',approvals,CheckCircle2],['Cash Points',cash,Warehouse],['Agents',agents,Store],['Staff Onboarding',staffOnboarding,ClipboardCheck],['Training Modules',training,GraduationCap]];
 return <div><h1 className="text-4xl font-black text-purple-950">AILIFE Command Center</h1><p className="mt-2 text-slate-600">AILIFE-specific remote monitoring for branches, staff onboarding, client onboarding, loans, savings, alerts and reporting.</p><div className="mt-8 grid gap-5 md:grid-cols-4">{cards.map(([t,v,Icon])=><div className="card p-6" key={t}><Icon className="text-purple-800"/><div className="mt-4 text-sm font-bold text-slate-500">{t}</div><div className="text-4xl font-black">{v}</div></div>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="text-xl font-black">Daily Money Movement Snapshot</h2><div className="mt-5 grid grid-cols-2 gap-4"><div className="rounded-2xl bg-green-50 p-5"><div className="text-sm font-bold text-green-700">Approved Deposits</div><div className="text-3xl font-black">₦{deposits.toLocaleString()}</div></div><div className="rounded-2xl bg-amber-50 p-5"><div className="text-sm font-bold text-amber-700">Approved Withdrawals</div><div className="text-3xl font-black">₦{withdrawals.toLocaleString()}</div></div></div></div><div className="card p-6"><h2 className="text-xl font-black">AILIFE Controls Now Built In</h2><ul className="mt-4 grid gap-2 text-sm text-slate-700 md:grid-cols-2"><li>✓ Osun, Ibadan & Port Harcourt branch setup</li><li>✓ Inactive branch support</li><li>✓ Daily, weekly & monthly loans</li><li>✓ 4% loan fee engine</li><li>✓ 5% monthly default penalty policy</li><li>✓ Credit Officer → Branch Manager → Area/Program Director workflow</li><li>✓ Staff onboarding</li><li>✓ Client onboarding</li><li>✓ Staff training modules</li><li>✓ Staff/branch portfolio reporting</li><li>✓ Credit bureau-ready configuration</li><li>✓ Internal risk scoring before credentials</li><li>✓ Manual credit review queue</li></ul></div></div></div>
}
