export const dynamic = 'force-dynamic'
import { countRows } from '@/lib/db'
import { Users, Banknote, ReceiptText, ShieldAlert, Scale, CheckCircle2, Building2, FileText, Bell, SearchCheck, WalletCards, Landmark } from 'lucide-react'

export default async function Dashboard(){
 const [branches,customers,loanProducts,applications,loans,repayments,tx,alerts,ledger,approvals,staff,docs,bureau,savings]=await Promise.all([
  countRows('branches'),countRows('customers'),countRows('loan_products'),countRows('loan_applications'),countRows('loans'),countRows('repayments'),countRows('transactions'),countRows('fraud_alerts'),countRows('ledger_entries'),countRows('approval_workflows'),countRows('staff_profiles'),countRows('documents'),countRows('credit_bureau_requests'),countRows('savings_accounts')
 ]);
 const cards=[
  ['Branches',branches,Building2],['Staff Profiles',staff,Users],['Customers',customers,Users],['Loan Products',loanProducts,Landmark],['Loan Applications',applications,Banknote],['Active Loans',loans,Banknote],['Repayments',repayments,ReceiptText],['Transactions',tx,ReceiptText],['Credit Bureau Requests',bureau,SearchCheck],['Open Fraud Alerts',alerts,ShieldAlert],['Ledger Entries',ledger,Scale],['Pending Approvals',approvals,CheckCircle2],['Documents',docs,FileText],['Savings Accounts',savings,WalletCards]
 ];
 return <div><h1 className="text-4xl font-black text-purple-950">AIBLE Command Center</h1><p className="mt-2 text-slate-600">Production dashboard for branches, staff, customer onboarding, loan workflow, repayments, credit bureau readiness and governance.</p><div className="mt-8 grid gap-5 md:grid-cols-4">{cards.map(([t,v,Icon])=><div className="card p-6" key={t}><Icon className="text-purple-800"/><div className="mt-4 text-sm font-bold text-slate-500">{t}</div><div className="text-4xl font-black">{v}</div></div>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="text-xl font-black">Build Flow</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm text-slate-700"><li>Seed loan products and chart of accounts.</li><li>Create first staff login from /staff-setup.</li><li>Onboard staff from Staff Management.</li><li>Onboard customers from Open Account or Customers/KYC.</li><li>Create loan application, approval, disbursement and repayment workflow.</li><li>Connect CreditRegistry API when credentials arrive.</li></ol></div><div className="card p-6"><h2 className="text-xl font-black">CreditRegistry Readiness</h2><ul className="mt-4 grid gap-2 text-sm text-slate-700"><li>✓ Credit bureau request table created</li><li>✓ Consent flags added for customer profiles</li><li>✓ API request/response JSONB storage ready</li><li>✓ SMARTScore/report fields ready</li><li>✓ Manual review and maker-checker workflow ready</li><li>✓ Audit trail ready</li></ul></div></div></div>
}
